# Generated by Django 5.0.4 on 2024-04-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='quantitiy',
        ),
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
